---
name: Lint OCSF Metaschema

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main

# Cancel in-progress runs when a new workflow with the same ID is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint OCSF Metaschema
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Spellcheck all content
        uses: streetsidesoftware/cspell-action@v7
        with:
          config: .github/.cspell.yaml
          strict: false
          inline: warning