name: Release OCSF Schema

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Print the release tag
        run: echo "${{ github.event.release.tag_name }}"
