name: 'Test PR with OCSF Server'

on:
  workflow_dispatch:
  push: 
  pull_request:
    branches:    
      - main
      - action

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir Step by Step
        run: |
          wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
          sudo apt-get update
          sudo apt-get install esl-erlang
          sudo apt-get install elixir

      - name: Clone OCSF Server
        run: git clone --recurse-submodules https://github.com/magnologan/ocsf-server.git 

      - name: Install the build tools
        run: mix local.hex --force && mix local.rebar --force

      - name: Get the dependencies
        run: |
          cd ocsf-server
          mix do deps.get, deps.compile

      - name: Compile the source code
        run: |
          mix compile

      - name: Run the schema server
        run: |
          SCHEMA_DIR=modules/schema SCHEMA_EXTENSION=extensions iex -S mix phx.server
