name: 'Test PR'

on:
  pull_request:
    branches:    
     - action

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Elixir and inotify
        run: |
          wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
          sudo apt-get update 
          sudo apt-get upgrade
          sudo apt-get install esl-erlang
          sudo apt-get install elixir
          sudo apt-get install inotify-tools
      
      - name: Checkout OCSF Schema
        uses: actions/checkout@v3
        
      - name: Check modified files
        run: |
          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{github.event.pull_request.number}}/files"
          
          FILES=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" -s -X GET -G $URL | jq -r '.[] | .filename')
          echo $FILES

      - name: Clone OCSF Server
        uses: actions/checkout@v3 
        with:
          repository: magnologan/ocsf-server
          submodules: "recursive"
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ocsf-server

      - name: Install the build tools
        run: mix local.hex --force && mix local.rebar --force

      - name: Get the dependencies and Compile the source code
        run: |
          cd ocsf-server
          mix do deps.get, deps.compile
          mix compile

      - name: Run the schema server
        run: |
          cd ocsf-server
          SCHEMA_DIR=modules/schema SCHEMA_EXTENSION=extensions iex -S mix phx.server
